name = "MyPublicPkg"
uuid = "a6e8d7c3-1fe2-45dc-81fa-a6c45a4fa21b"
authors = [""]
version = "1.2.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
