name: Tests & Coverage
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    uses: MyExampleOrg/.CI/.github/workflows/Coverage.yml@master
    with:
      registers: "https://${{ secrets.REGISTRATOR_TOKEN_3 }}@github.com/MyExampleOrg/MyPrivateRegistry.git"
