name: Update public registry 2
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: MyExampleOrg/MyPublicRegistry/.github/actions/update-registry/action.yml@master
        with:
          token: ${{ secrets.REGISTRATOR_TOKEN_2 }}
        
