name: Update public registry
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  registry:
    uses: MyExampleOrg/MyPublicRegistry/.github/workflows/Registry.yml@master
    secrets: inherit
