name: Update public registry
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
jobs:
  registry:
    uses: MyExampleOrg/.CI/.github/workflows/Registry.yml@master
    with:
      registers: MyExampleOrg/MyPublicRegistry
      target_registry: MyExampleOrg/MyPublicRegistry
    secrets:
      token: ${{ secrets.REGISTRATOR_TOKEN_2 }}
