name: Update public registry
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: MyExampleOrg/.actions/update-registry@master
        with:
          token: ${{ secrets.REGISTRATOR_TOKEN_2 }}
          registry: ${{ vars.PUBLIC_REGISTRY_PATH }}
